# Generated by Django 2.0.6 on 2020-03-29 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('nombre_interno', models.CharField(max_length=255)),
                ('numero_registro', models.IntegerField()),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEstacion', models.CharField(max_length=45)),
                ('nombreEstacion', models.CharField(max_length=45)),
                ('latitud', models.CharField(max_length=45)),
                ('longitud', models.CharField(max_length=45)),
                ('altitud', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('entidad', models.CharField(max_length=45)),
                ('areaOperativa', models.CharField(max_length=45)),
                ('departamento', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('fechaInstalacion', models.DateField(blank=True, null=True)),
                ('fechaSuspension', models.DateField(blank=True, null=True)),
                ('idParametro', models.CharField(max_length=45)),
                ('etiqueta', models.CharField(max_length=45)),
                ('descripcionSerie', models.CharField(max_length=45)),
                ('frecuencia', models.CharField(max_length=45)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grado', models.CharField(max_length=45)),
                ('calificador', models.CharField(max_length=45)),
                ('nivelAprovacion', models.CharField(max_length=45)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Archivo')),
            ],
            options={
                'db_table': 'informacion',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Usuarios'),
        ),
    ]
